version: "3.8"

services:
  app:
    container_name: ipsum_hdv
    build:
      context: .
      dockerfile: ./apps/app/Dockerfile
    environment:
        - DATABASE_URL=${DATABASE_URL}
        - API_PASSWORD=${API_PASSWORD}
    restart: always
    ports:
      - 3055:3000
    networks:
      - app_network
      
networks:
  app_network:
    external: true
