export enum EJob {
  None = -1,
  Bucheron = 2,
  ForgeurEpees = 11,
  SculpteurArcs = 13,
  ForgeurMarteaux = 14,
  Cordonnier = 15,
  Bijoutier = 16,
  ForgeurDague = 17,
  SculpteurBaton = 18,
  SculpteurBaguette = 19,
  ForgeurPelle = 20,
  Mineur = 24,
  Boulanger = 25,
  Alchimiste = 26,
  Tailleur = 27,
  Paysans = 28,
  ForgeurHache = 31,
  Pecheur = 36,
  Chasseur = 41,
  Boucher = 56,
  Poissonier = 58,
  Faconneur = 60,
  Bricoleur = 65,
}

export const jobsFilter = [
  { name: 'Aucun filtre', jobId: -1 },
  { name: 'Bûcheron', jobId: EJob.Bucheron },
  { name: "Forgeur d'Epées", jobId: EJob.ForgeurEpees },
  { name: "Sculpteur d'Arcs", jobId: EJob.SculpteurArcs },
  { name: 'Forgeur de Marteaux', jobId: EJob.ForgeurMarteaux },
  { name: 'Cordonnier', jobId: EJob.Cordonnier },
  { name: 'Bijoutier', jobId: EJob.Bijoutier },
  { name: 'Forgeur de Dagues', jobId: EJob.ForgeurDague },
  { name: 'Sculpteur de Bâtons', jobId: EJob.SculpteurBaton },
  { name: 'Sculpteur de Baguettes', jobId: EJob.SculpteurBaguette },
  { name: 'Forgeur de Pelles', jobId: EJob.ForgeurPelle },
  { name: 'Mineur', jobId: EJob.Mineur },
  { name: 'Boulanger', jobId: EJob.Boulanger },
  { name: 'Alchimiste', jobId: EJob.Alchimiste },
  { name: 'Tailleur', jobId: EJob.Tailleur },
  { name: 'Paysans', jobId: EJob.Paysans },
  { name: 'Forgeur de Haches', jobId: EJob.ForgeurHache },
  { name: 'Pêcheur', jobId: EJob.Pecheur },
  { name: 'Chasseur', jobId: EJob.Chasseur },
  { name: 'Boucher', jobId: EJob.Boucher },
  { name: 'Poissonier', jobId: EJob.Poissonier },
  { name: 'Façonneur', jobId: EJob.Faconneur },
  { name: 'Bricoleur', jobId: EJob.Bricoleur },
];
